### ISSUE TITLE
Can't drag and drop files

### ISSUE THREAD

**Issue by MegAmi24** [leamsii/Shovel-Knight-Packer#7]
Even with all the dependencies installed, Windows Explorer doesn't allow me to drag and drop files into the .py files, rendering the tool useless. I have no idea how to use the tool using a command prompt either as that isn't documented.

**Comment by leamsii** [comment]
Open command prompt and change directory to the .py file. Type ppacker.py target.pak. Let me know what it says.

**Comment by MegAmi24** [comment]
> Open command prompt and change directory to the .py file. Type ppacker.py target.pak. Let me know what it says.

I've already tried this and it doesn't seem to read the file at all

**Comment by leamsii** [comment]
Can you show me a screenshot of what it outputs ?

**Comment by MegAmi24** [comment]
![image](https://user-images.githubusercontent.com/7158344/70949313-15359a00-2023-11ea-9ac1-22a55e407568.png)
Here you go.

**Comment by leamsii** [comment]
![cmd](https://user-images.githubusercontent.com/10819862/70951475-811eff00-2031-11ea-8337-865a7f26af65.PNG)

Run it like this, no spaces after the your_file.pak

If that doesn't work, I just pushed a new update, download it and try again.

**Comment by MegAmi24** [comment]
I don't get it. I've been running it exactly like that. Am I typing in a character wrong?

The update didn't solve anything.

**Comment by leamsii** [comment]
Something's odd about your setup. Honestly everything looks fine, try it without running as admin.

**Comment by MegAmi24** [comment]
After lots of time and sweat, I finally figured out and fixed the issue.

The .py extension's default program was set to the wrong program the whole time.

The tool works now.
